name: in_app_update
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.axon.in_app_update
        pluginClass: InAppUpdatePlugin
      ios:
        pluginClass: InAppUpdatePlugin
